# Generated by Django 3.0.5 on 2020-04-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='test', max_length=256)),
                ('snippet', models.CharField(default='test', max_length=256)),
                ('language', models.CharField(default='test', max_length=256)),
                ('description', models.CharField(blank=True, default='test', max_length=256, null=True)),
            ],
        ),
    ]
