# Generated by Django 3.0.5 on 2020-04-24 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 19, 29, 44, 710471, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='snippet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 19, 29, 44, 710541, tzinfo=utc)),
        ),
    ]
